name: Release
"on":
  workflow_dispatch
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@main
        with:
          allowed-endpoints: 
            artifactcache.actions.githubusercontent.com.:443
            4qfyacprodeus2file2.blob.core.windows.net.:443
            github.com.:443
            registry.npmjs.org.:443
            beta.api.stepsecurity.io:443
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  
