name: Release
"on":
  workflow_dispatch
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: step-security/test@main
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
